import Resultado from '@/components/Resultado'
import Sidebar from '@/components/Sidebar'
import useSearchCountryEngine from '@/hooks/useSearchCountryEngine'
import React from 'react'

function buscarPorCapital() {
    const {numero,nombreCapital,handleNombreCapital,paises}=useSearchCountryEngine();

   // console.log("CAPITAL:",nombreCapital);
    return (
    <div>

        <title>Search Country Engine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossOrigin="anonymous"/>
        <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
      

    <div className='row container mt-4'>
    <div className='col-3'>
      <Sidebar/>
    </div>

    <div className='col'>
    <h2>Por Capital</h2>
    <hr/>
<div className="row">
  <div className="col">
        <form>
            <input type='text' onChange={(e)=>handleNombreCapital(e.target.value)} className='form-control' id="termino"/>
        </form>
  </div>
</div>

<hr/>
 <div className='row'>
    <div className='col'>
        
      <Resultado
        
        />
    </div>
 </div>
    </div>
      
   
  
  </div>
    
    </div>
  )
}

export default buscarPorCapital